// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeHist struct {
	_       structs.HostLayout
	Latency uint64
	Cnt     uint64
	Slots   [27]uint32
	_       [4]byte
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	TcpRcv *ebpf.ProgramSpec `ebpf:"tcp_rcv"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Hists *ebpf.MapSpec `ebpf:"hists"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	TargDaddr     *ebpf.VariableSpec `ebpf:"targ_daddr"`
	TargDport     *ebpf.VariableSpec `ebpf:"targ_dport"`
	TargLaddrHist *ebpf.VariableSpec `ebpf:"targ_laddr_hist"`
	TargMs        *ebpf.VariableSpec `ebpf:"targ_ms"`
	TargRaddrHist *ebpf.VariableSpec `ebpf:"targ_raddr_hist"`
	TargSaddr     *ebpf.VariableSpec `ebpf:"targ_saddr"`
	TargShowExt   *ebpf.VariableSpec `ebpf:"targ_show_ext"`
	TargSport     *ebpf.VariableSpec `ebpf:"targ_sport"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Hists *ebpf.Map `ebpf:"hists"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Hists,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	TargDaddr     *ebpf.Variable `ebpf:"targ_daddr"`
	TargDport     *ebpf.Variable `ebpf:"targ_dport"`
	TargLaddrHist *ebpf.Variable `ebpf:"targ_laddr_hist"`
	TargMs        *ebpf.Variable `ebpf:"targ_ms"`
	TargRaddrHist *ebpf.Variable `ebpf:"targ_raddr_hist"`
	TargSaddr     *ebpf.Variable `ebpf:"targ_saddr"`
	TargShowExt   *ebpf.Variable `ebpf:"targ_show_ext"`
	TargSport     *ebpf.Variable `ebpf:"targ_sport"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	TcpRcv *ebpf.Program `ebpf:"tcp_rcv"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.TcpRcv,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
